spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imjang_db
    username: marista
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: never
server:
  port: 8080

logging:
  level:
    com.imjang: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
